Feature/ingredient
Arnasst/PoSSapi pull request #6
Opened 2022-12-21 10:04 UTC by kristupas-g

2022-12-21 12:21 UTC, Arnasst commented on PoSSapi/src/WebUI/Controllers/IngredientController.cs
> +    }
These 3 gets seem like a single endpoint with some query parameters

2022-12-21 12:21 UTC, Arnasst commented on PoSSapi/src/WebUI/Controllers/IngredientController.cs
> +    public async Task<ActionResult<IQueryable<Ingredient>>> GetAllIngredientsPaginatedQuery([FromQuery] GetAllIngredientsQuery query)
And this should be a paginated list

2022-12-29 17:34 UTC, Arnasst requested changes
Previous comments have not been fixed

2023-01-02 15:04 UTC, baikauskaite commented on PoSSapi/src/Application/Ingredients/Queries/GetIngredientByNameQuery.cs
> +using MediatR;
This file doesn't seem to be used anywhere

2023-01-02 15:04 UTC, baikauskaite commented on PoSSapi/src/Application/Ingredients/Commands/UpdateIngredientCommandValidator.cs
> +using FluentValidation;
Maybe put this file to a `Validators` folder? We're doing this elsewhere in the project.

2023-01-02 15:04 UTC, baikauskaite commented on PoSSapi/src/Application/Ingredients/Commands/CreateIngredientCommandValidator.cs
> +using FluentValidation;
Put this file to `Validators` folder?

2023-01-02 15:38 UTC, baikauskaite approved these changes

2023-01-02 15:38 UTC, merged